### ISSUE TITLE
Missing credit?

### ISSUE THREAD

**Issue by lstor** [csvoss/oneliner#1]
If this is based on [On Writing Python One-liners](http://blog.sigfpe.com/2008/09/on-writing-python-one-liners.html), then I think you should do the proper credits in the README.

If it *isn't*, then I still think it would be worth mentioning.

**Comment by csvoss** [comment]
It is not based on that -- but thank you for the link!

**Comment by csvoss** [comment]
Added to the README.

**Comment by lstor** [comment]
Great :smile:
