### ISSUE TITLE
Unable to recompile main.ol.py from current version of main.py

### ISSUE THREAD

**Issue by csvoss** [csvoss/oneliner#29]
First, remove `try...except` blocks and `if __name__ == '__main__'` in `main.py` in order to create something that can be compiled to one line. Once that's taken care of, I can compile a new `main.ol.py`, but it has some bugs. For example, the resulting `main.ol.py` does not correctly compile these programs:

```
print "Hello world!"
print "Hi."
```
— compiles into something which omits the second print statement.

```
print "Hello, world!"
x = 4
y = 5
print x + y
```
— cannot be compiled by `main.ol.py`, because `main.ol.py` errors with `AttributeError: 'Name' object has no attribute 'op'`.

**Comment by andersk** [comment]
Although I haven’t actually debugged this, it seems pretty hopeless until #17 is fixed: the lack of local variables really makes recursion difficult. I have a plan, but it’s going to make this a little worse before it gets better…

**Comment by csvoss** [comment]
Currently blocking on: we cannot include template.py without the recursion depth exceeding what Python will allow (and we need to obey the recursion depth, because pypy doesn't have an implementation of symtable).

**Comment by csvoss** [comment]
We fixed this by fixing globals(): one-lined modules now export their variables, so main_ol.py can import from template_ol.py and everything is happy.
