### ISSUE TITLE
Idea for exec

### ISSUE THREAD

**Issue by asottile** [csvoss/oneliner#4]
At least in python2 you can replace exec with execfile and some tempfile trickery.  In python3 (which I notice isn't planned / supported yet) you can just use exec directly.

**Comment by csvoss** [comment]
Nice! Yeah, this is Python 2. 

I'll keep this in mind -- you're also welcome to try to implement it if you like.

I also wonder whether it's possible to grab `exec` from Python 3 in a way similar to the way that I grabbed `print` from Python 3.

**Comment by asottile** [comment]
I tried poking at exec and it seems they only put print into builtins to support `from __future__ import print_function` but didn't think to do exec as well :(

**Comment by andersk** [comment]
A standard library solution is `exec body, globals, locals` → `trace.Trace(count=False, trace=False).runctx(body, globals, locals)`.
